Price Point = SWITCH(TRUE(),
'Product Lookup'[ProductPrice] > 500,"High",
'Product Lookup'[ProductPrice] > 100,"Medium",
"Low")



SKU Category = LEFT('Product Lookup'[ProductSKU],SEARCH("-",'Product Lookup'[ProductSKU])-1)


QuantityType = IF(
    'Sales Data'[OrderQuantity] > 1 ,"Mutliple Items", "Single Item")


Retail Price = RELATED('Product Lookup'[ProductPrice])

Education Category = SWITCH('Customer Lookup'[EducationLevel],
"High School", "High School",
"Partial High School","High School",
"Bachelors","Undergrad",
"Partial College","Undergrad",
"Graduate Degree","Graduate")

Month Short = UPPER(LEFT('Calendar Lookup'[Month Name],3))

Weekend = IF( 'Calendar Lookup'[Day of Week] IN {6,7}, "Weekend","Weekday")

Weekend Orders = CALCULATE([Total Orders],'Calendar Lookup'[Weekend] = "Weekend")

///////////////////////////////////////////////////////////////////////////////////////////

YTD Revenue = CALCULATE([Total Revenue],DATESYTD('Calendar Lookup'[Date]))

// Time Intelligence patterns are used to calculate common date-based comparisons


// Performance To-Date: Use DATESYTD for Years, DATESQTD for Quarters, DATESMTD for Months
=CALCULATE(Measure, DATESYTD(Calendar[Date]))

// Previous Period: Select an interval (DAY, MONTH, QUARTER, or YEAR)
// and the # of intervals to compare (e.g. previous month, rolling 10-day)
=CALCULATE(Measure, DATEADD(Calendar[Date], -1, MONTH))


// Running Total:
=CALCULATE(Measure, DATESINPERIOD(Calendar[Date], MAX(Calendar[Date]), -10, DAY))

// PRO TIP: To calculate a moving average, use the running total calculation above and divide by the number of intervals


//////////////////////////////////////////////////////////////////////////////////////////////